### ISSUE TITLE
Remove `enumerize` gem

### ISSUE THREAD

**Issue by mathieugagne** [montrealrb/Montreal.rb#128]
### Open for discussion

Is there any advantages to using the `enumerize` gem instead of `ActiveRecord::Enum`?

[http://api.rubyonrails.org/classes/ActiveRecord/Enum.html](http://api.rubyonrails.org/classes/ActiveRecord/Enum.html)

I traced the inclusion of `enumerize` to this commit: 2215ebc49f1251f82f6be14d1b946ff483477e69

I would suggest we remove `enumerize` in favor of `ActiveRecord::Enum`

The one reason I found for `enumerize` was it's integration with I18n for translation. But I only see this being useful in the backend. Attributes would be easy to translate on our frontend views.

TODO:
- Remove `enumerize` from the Gemfile
- Database migrations for enum fields from string to integer
- Add default db state value of `0` to avoid `null` states
- Remove custom `published` scope
- Clean up `Job`, `Event` and `NewsItem`

![Who's with me?](http://cdn.meme.am/instances/57979558.jpg)

**Comment by benichu** [comment]
I would add that storing enum values as string instead as integer, it's pretty useful when you have to read/import data at a later stage, without the code as business logic... But that's coming from someone who just had to import our old wordpress posts, and appreciated `post_status = 'published'` vs `post_status = 1`

**Comment by mathieugagne** [comment]
@benichu Good point :+1: 

Hopefully we won't have to do that again

**Comment by cawel** [comment]
I feel I have to jump in here because I was among those who agreed with @benichu that we should use the `enumerize` gem. However, I learnt later that [`enum`](http://api.rubyonrails.org/classes/ActiveRecord/Enum.html) was actually [part of rails since 4.1.0](https://robots.thoughtbot.com/whats-new-in-edge-rails-active-record-enum). And along the years, I have learnt to refrain from using gems which do not add signifiant value to a project (more on that around a :beer:). All that to say that I also share @mathieugagne 's motivation to jettison that dependency. Although surely in a less warmongering fashion ;)

![3214029](https://cloud.githubusercontent.com/assets/15407/11610133/b3096f8a-9b67-11e5-9fa3-061a23d79ae9.jpg)

Observation: assuming the admin interface will be English-only, so far all enum fields in the codebase do not need to be translated, since they are only relevant on the server-side, specifying a resource state ('draft', 'archived', 'published').

However, if an enum field does need to see the outside (French) world, then the i18n-support argument might be suffisant in itself. Since we will be rendering the views on the server side, fetching the translations from the i18n files would be quite handy.

@mathieugagne : you said "Attributes would be easy to translate on our frontend views". Could you be more specific? Did you mean that we could code a simple view helper method which would take an enum field as an argument and would fetch the translation from the i18n files?

**Comment by mathieugagne** [comment]
@cawel helper method might not be needed. Would have to test but I'd guess they'd be a convention for activerecord attributes with regards to I18n keys.

That being said, I don't see where on the website would we advertise the state of our jobs/articles. IMO they're very backend attributes and won't even need translation.

You're meme is fantastic! We should reuse it whenever new gens reappear lol

**Comment by AndyObtiva** [comment]
@cawel I like how you've taken up a nighttime acting job. When is that movie coming out? I bet its mention of gems would rival any mention of rings in LOTR. :) :+1: 

And yes, enums are now part of Rails, so :+1: indeed.

p.s. BTW, enums in any shape or form can be internationalized by feeding their values to I18n.t (though I'm probably being redundant as that was mentioned already).

**Comment by karimmtarek** [comment]
@montrealrb/contributors so what it is the final decision? I'm working on this #60 and I've couple of things needs to be Enum, so should I go with the gem? or Rails's Enum, put in mind if used Rails's Enum then each element needs to be an integer and maps to a string I think, if that will upset @benichu :) what about using [this](https://gist.github.com/alexch/a7be54e1b085718473ff)?

**Comment by nicholasjhenry** [comment]
@cawel Just wanted to let you know I'm having a giggle at this considering our discussion regarding `friendly_id` ;-)

https://github.com/montrealrb/Montreal.rb/issues/128#issuecomment-162250720

**Comment by nicholasjhenry** [comment]
Thanks for this discussion -- I'm in favour of keeping `enumerize` for now mainly for the explicitness -- not having to make a translation between integers.
