### ISSUE TITLE
Manage and display pages

### ISSUE THREAD

**Issue by sophiedeziel** [montrealrb/Montreal.rb#35]
We need pages of content (separated from the news feed) for special content (about, FAQs, howtos)

- [x] manage pages in the admin
- [ ] access pages via a link

**Comment by kiramclean** [comment]
I've got this with @cawel

**Comment by cawel** [comment]
For the MVP, I assume having some `HTML` code persisted into a db field for the page content is good enough?

**Comment by nicholasjhenry** [comment]
That's fine for this pull-request. We'll look at adding Markdown across the board for all content models once they're merged in.

**Comment by cawel** [comment]
Awesome :+1:

**Comment by nicholasjhenry** [comment]
- [ ] The outstanding task for this is to be able to link to a page via a slug. For example `pages_path("about")`

**Comment by cawel** [comment]
> For example `page_path("about")`

Since [we agreed](https://github.com/montrealrb/Montreal.rb/pull/85) that we would *not* use the [friendly_id gem](https://github.com/norman/friendly_id) for now, I don't see how this can be possible (without overloading something like the `url_for` method), unless you know the page id, e.g. `page_path('1-about')`.

I see a few options:

* Accept to use `page_path('1-about')`
* Add a method in the `Page` class which would return the page id, and do that for each "static page" we have, e.g. `page_path(Page.about)`
* Start using the `friendly_id` gem, so that we could do `page_path('about')` where "about" would be the slug for the About page.
* Use the [High Voltage gem](https://github.com/thoughtbot/high_voltage) (as @sophiedeziel recommended earlier) would make using `page_path('about')` a breeze, but then the code to manage the pages in the admin interface (also a [feature requirement](https://github.com/montrealrb/Montreal.rb/issues/35#issue-114960858)) would be cumbersome (especially on heroku) because we would have to manage _files_, as opposed to regular db model fields.

**Comment by nicholasjhenry** [comment]
Could we not add a `slug` (required) attribute to page that the admin specifies?

**Comment by cawel** [comment]
@nicholasjhenry We could, but then we'd need to write some custom "resource lookup code" in the controller.

Using a dedicated db field to manage what is shown in the url is the implementation solution from the `friendly_id` gem. So maybe we reached the point where we should bring in that gem?

**Comment by nicholasjhenry** [comment]
>  custom "resource lookup code" in the controller

Do you mean?:

```ruby
@page = Page.find_by!(slug: params[:slug])
```

**Comment by cawel** [comment]
Yes. To me, that looks like a lesser solution than what the `friendly_id` gem does. E.g. what if that `slug` field contains invalid characters?

To compare, the `friendly_id` way is:

```ruby
User.friendly.find(params[:id])
```

**Comment by nicholasjhenry** [comment]
Feel free to submit a PR :-)

**Comment by benichu** [comment]
I would personally consider using `friendly_id` if only for that feature: http://norman.github.io/friendly_id/FriendlyId/History.html

**Comment by cawel** [comment]
@benichu Hum. Should we interpret that comment as a vote to bring it on right about now, or rather later on down the road? ;)

**Comment by benichu** [comment]
I vote to bring it in now. :+1: 
Especially since it will probably help us clearing up the temporary hack I did when importing the old wordpress posts: https://github.com/montrealrb/Montreal.rb/blob/master/app/controllers/news_items_controller.rb#L6-L16

**Comment by nicholasjhenry** [comment]
Bring it!
