### ISSUE TITLE
Create a domain/data model

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#47]

**Comment by nicholasjhenry** [comment]
Based on the requirements listed in the issue tracker and the current database schema, I believe this accurately models the domain -- note that it does not address language requirements. 

![montreal-rb](https://cloud.githubusercontent.com/assets/40253/11310185/1a559fde-8f96-11e5-9e17-6ea7b315cd51.png)

I'm not suggesting we need to something as complicated as this, but it does give us a high-level view to discuss further. Questions and feedback welcome!

**Comment by benichu** [comment]
It definitely gives us a clear overview of the domain, I'll look into it this weekend.

**Comment by mdeloupy** [comment]
This is great ! Thanks Nicholas !

**Comment by cawel** [comment]
Very useful :+1: 

Here are a few comments (which might be premature for a *high-level* db schema):

* In order to have url-friendly url's for the pages within the "content management", it would be nice to have some slugs (hence, columns).
* The pages within the "content management" could be linked to the `User` model, e.g. an `author_id` field (as an alias to the `user_id` column).
* In order to support the RSVP feature (issue #22), don't we need another table? A candidate implementation might be a many-to-many table between `Event` and `Member`.

I'm pretty sure we'll discuss some of those points tonight, during the workshop.

**Comment by nicholasjhenry** [comment]
> which might be premature for a high-level db schema

It's more an object model, than a DB schema focused on persistence -- hence no foreign keys, join tables etc. @cawel But theses are all great suggestions. Thank you! :boom:

> In order to have url-friendly url's for the pages within the "content management", it would be nice to have some slugs (hence, columns).

Yes, definitely.

> The pages within the "content management" could be linked to the User model, e.g. an author_id field (as an alias to the user_id column).

Yes, definitely. Probably makes most sense for `Event`, `NewsItem` and `Page`.

> In order to support the RSVP feature (issue #22), don't we need another table? A candidate implementation might be a many-to-many table between Event and Member.

Yes, to persist the many-to-many relationship we would definitely need a join table.
